// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/pb/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomFloat64Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFloat64Request) Reset() {
	*x = GetRandomFloat64Request{}
	mi := &file_pkg_pb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFloat64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFloat64Request) ProtoMessage() {}

func (x *GetRandomFloat64Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFloat64Request.ProtoReflect.Descriptor instead.
func (*GetRandomFloat64Request) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{0}
}

type GetRandomFloat64Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        float64                `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFloat64Response) Reset() {
	*x = GetRandomFloat64Response{}
	mi := &file_pkg_pb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFloat64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFloat64Response) ProtoMessage() {}

func (x *GetRandomFloat64Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFloat64Response.ProtoReflect.Descriptor instead.
func (*GetRandomFloat64Response) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomFloat64Response) GetNumber() float64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetRandomInt64Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomInt64Request) Reset() {
	*x = GetRandomInt64Request{}
	mi := &file_pkg_pb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomInt64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomInt64Request) ProtoMessage() {}

func (x *GetRandomInt64Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomInt64Request.ProtoReflect.Descriptor instead.
func (*GetRandomInt64Request) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetRandomInt64Request) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *GetRandomInt64Request) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type GetRandomInt64Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomInt64Response) Reset() {
	*x = GetRandomInt64Response{}
	mi := &file_pkg_pb_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomInt64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomInt64Response) ProtoMessage() {}

func (x *GetRandomInt64Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomInt64Response.ProtoReflect.Descriptor instead.
func (*GetRandomInt64Response) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetRandomInt64Response) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetDeterministicRandomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Probabilities []float64              `protobuf:"fixed64,2,rep,packed,name=probabilities,proto3" json:"probabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeterministicRandomRequest) Reset() {
	*x = GetDeterministicRandomRequest{}
	mi := &file_pkg_pb_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeterministicRandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeterministicRandomRequest) ProtoMessage() {}

func (x *GetDeterministicRandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeterministicRandomRequest.ProtoReflect.Descriptor instead.
func (*GetDeterministicRandomRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeterministicRandomRequest) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GetDeterministicRandomRequest) GetProbabilities() []float64 {
	if x != nil {
		return x.Probabilities
	}
	return nil
}

type GetDeterministicRandomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeterministicRandomResponse) Reset() {
	*x = GetDeterministicRandomResponse{}
	mi := &file_pkg_pb_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeterministicRandomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeterministicRandomResponse) ProtoMessage() {}

func (x *GetDeterministicRandomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeterministicRandomResponse.ProtoReflect.Descriptor instead.
func (*GetDeterministicRandomResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeterministicRandomResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_pkg_pb_service_proto protoreflect.FileDescriptor

const file_pkg_pb_service_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/pb/service.proto\x12\x06random\"\x19\n" +
	"\x17GetRandomFloat64Request\"2\n" +
	"\x18GetRandomFloat64Response\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x01R\x06number\";\n" +
	"\x15GetRandomInt64Request\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"0\n" +
	"\x16GetRandomInt64Response\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\"a\n" +
	"\x1dGetDeterministicRandomRequest\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12$\n" +
	"\rprobabilities\x18\x02 \x03(\x01R\rprobabilities\"8\n" +
	"\x1eGetDeterministicRandomResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number2\x99\x02\n" +
	"\x06Random\x12U\n" +
	"\x10GetRandomFloat64\x12\x1f.random.GetRandomFloat64Request\x1a .random.GetRandomFloat64Response\x12O\n" +
	"\x0eGetRandomInt64\x12\x1d.random.GetRandomInt64Request\x1a\x1e.random.GetRandomInt64Response\x12g\n" +
	"\x16GetDeterministicRandom\x12%.random.GetDeterministicRandomRequest\x1a&.random.GetDeterministicRandomResponseB\x80\x01\n" +
	"\n" +
	"com.randomB\fServiceProtoP\x01Z,github.com/fasttrack-solutions/random/pkg/pb\xa2\x02\x03RXX\xaa\x02\x06Random\xca\x02\x06Random\xe2\x02\x12Random\\GPBMetadata\xea\x02\x06Randomb\x06proto3"

var (
	file_pkg_pb_service_proto_rawDescOnce sync.Once
	file_pkg_pb_service_proto_rawDescData []byte
)

func file_pkg_pb_service_proto_rawDescGZIP() []byte {
	file_pkg_pb_service_proto_rawDescOnce.Do(func() {
		file_pkg_pb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_service_proto_rawDesc), len(file_pkg_pb_service_proto_rawDesc)))
	})
	return file_pkg_pb_service_proto_rawDescData
}

var file_pkg_pb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_pb_service_proto_goTypes = []any{
	(*GetRandomFloat64Request)(nil),        // 0: random.GetRandomFloat64Request
	(*GetRandomFloat64Response)(nil),       // 1: random.GetRandomFloat64Response
	(*GetRandomInt64Request)(nil),          // 2: random.GetRandomInt64Request
	(*GetRandomInt64Response)(nil),         // 3: random.GetRandomInt64Response
	(*GetDeterministicRandomRequest)(nil),  // 4: random.GetDeterministicRandomRequest
	(*GetDeterministicRandomResponse)(nil), // 5: random.GetDeterministicRandomResponse
}
var file_pkg_pb_service_proto_depIdxs = []int32{
	0, // 0: random.Random.GetRandomFloat64:input_type -> random.GetRandomFloat64Request
	2, // 1: random.Random.GetRandomInt64:input_type -> random.GetRandomInt64Request
	4, // 2: random.Random.GetDeterministicRandom:input_type -> random.GetDeterministicRandomRequest
	1, // 3: random.Random.GetRandomFloat64:output_type -> random.GetRandomFloat64Response
	3, // 4: random.Random.GetRandomInt64:output_type -> random.GetRandomInt64Response
	5, // 5: random.Random.GetDeterministicRandom:output_type -> random.GetDeterministicRandomResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_service_proto_init() }
func file_pkg_pb_service_proto_init() {
	if File_pkg_pb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_service_proto_rawDesc), len(file_pkg_pb_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_service_proto_goTypes,
		DependencyIndexes: file_pkg_pb_service_proto_depIdxs,
		MessageInfos:      file_pkg_pb_service_proto_msgTypes,
	}.Build()
	File_pkg_pb_service_proto = out.File
	file_pkg_pb_service_proto_goTypes = nil
	file_pkg_pb_service_proto_depIdxs = nil
}
